spring.datasource.url: jdbc:mysql://localhost:3306/ToDoListlib
spring.datasource.username: root
spring.datasource.password: vbhjplfybt161
spring.jpa.hibernate.ddl-auto: none
someParameter:
  value: 5463
